name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: |
          yarn lint:js
          yarn lint:hbs

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
        node: ["8", "10"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test --launch ${{ matrix.browser }}

  floating-dependencies:
    if: false # disable for now, there's no way we can get these green on Node 8
    name: Floating Dependencies
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --no-lockfile --non-interactive
    - name: Test
      run: yarn test --launch ${{ matrix.browser }}

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: ${{ matrix.allow-failure }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario: [
          ember-lts-3.4,
          ember-lts-3.8,
          #ember-release, # we are too far behind for these to pass
          #ember-beta,
          ember-default-with-jquery
        ]
        allow-failure: [false]
        #include:
        #  - ember-try-scenario: ember-canary
        #    allow-failure: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
